services:
  handymax:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}

    container_name: handymax

    expose:
      - "80"

    labels:
      traefik.enable: "true"
      traefik.http.routers.handymax.entrypoints: websecure
      traefik.http.routers.handymax.rule: Host(`instalaciones.multimax.net`)
      traefik.http.routers.handymax.tls.certresolver: letsencrypt
      traefik.http.services.handymax.loadbalancer.server.port: "80"
      traefik.docker.network: handymax_default

    networks:
      default: null

    restart: unless-stopped

networks:
  default:
    name: handymax_default
